services:
  lol-tracker:
    build:
      context: ..
      dockerfile: lol-tracker/Dockerfile
      target: production
    env_file:
      - ../.env
    environment:
      # Database configuration - use host's postgres in production
      DATABASE_URL: ${DATABASE_URL}
      
      # LoL Tracker configuration
      RIOT_API_KEY: ${RIOT_API_KEY}
      RIOT_API_BASE_URL: ${RIOT_API_BASE_URL:-https://na1.api.riotgames.com}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS:-60}
      
      # Message bus configuration
      MESSAGE_BUS_URL: ${MESSAGE_BUS_URL}
      
      # Environment
      ENVIRONMENT: production
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import asyncio; import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      start_period: 30s
      retries: 3