services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    environment:
      # Discord configuration
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DISCORD_GUILD_ID: ${DISCORD_GUILD_ID}
      
      # Database configuration - use host's postgres in production
      DATABASE_URL: ${DATABASE_URL}
      
      # Bot configuration
      INTEREST_RATE: ${INTEREST_RATE:-0.005}
      INTEREST_SCHEDULE: ${INTEREST_SCHEDULE:-0 0 * * *}
      STARTING_BALANCE: ${STARTING_BALANCE:-100000}
      
      # Environment
      ENVIRONMENT: production
      
    restart: unless-stopped
    network_mode: host  # Access host's postgres instance