services:
  # Single PostgreSQL instance with multiple databases
  postgres:
    image: postgres:16-alpine
    container_name: gambler-postgres
    environment:
      POSTGRES_USER: gambler
      POSTGRES_PASSWORD: gambler_dev_password
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-databases.sql:/docker-entrypoint-initdb.d/init-databases.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gambler -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gambler-network

  # Discord bot service
  discord-bot:
    container_name: discord-bot
    build:
      context: ./discord-client
      dockerfile: Dockerfile
      target: dev
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # Discord configuration
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      
      # Database configuration - use discord_db database
      DATABASE_URL: postgres://gambler:gambler_dev_password@postgres:5432/gambler_db?sslmode=disable
      
      # Bot configuration
      STARTING_BALANCE: ${STARTING_BALANCE:-100000}
      HIGH_ROLLER_ROLE_ID: ${HIGH_ROLLER_ROLE_ID}
      HIGH_ROLLER_ENABLED: true
      RESOLVER_DISCORD_IDS: ${RESOLVER_DISCORD_IDS}
      
      # Environment
      ENVIRONMENT: development
      LOG_LEVEL: debug
      
    volumes:
      - ./discord-client:/app
      - /app/tmp  # Exclude tmp directory
    working_dir: /app
    command: air
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - gambler-network

  # LoL Tracker service
  lol-tracker:
    container_name: lol-tracker
    build:
      context: .
      dockerfile: lol-tracker/Dockerfile
      target: development
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      # LoL Tracker configuration
      RIOT_API_KEY: ${RIOT_API_KEY}
      RIOT_API_BASE_URL: ${RIOT_API_BASE_URL:-https://na1.api.riotgames.com}
      POLL_INTERVAL_SECONDS: ${POLL_INTERVAL_SECONDS:-60}
      
      # Database configuration - use lol_tracker_db database
      DATABASE_URL: postgres://gambler:gambler_dev_password@postgres:5432/lol_tracker_db?sslmode=disable
      
      # Message bus configuration
      MESSAGE_BUS_URL: ${MESSAGE_BUS_URL}
      
      # Environment
      ENVIRONMENT: development
      LOG_LEVEL: debug
      
    volumes:
      - ./lol-tracker/src:/app/src
      - ./lol-tracker/tests:/app/tests
    working_dir: /app
    command: python -m lol_tracker.main
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - gambler-network

volumes:
  postgres_data:

networks:
  gambler-network:
    driver: bridge