name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moreshields/gamba-base:latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - service: discord-client
            dockerfile: discord-client/Dockerfile
            target: prod
            image: ${{ github.repository }}
          - service: lol-tracker
            dockerfile: lol-tracker/Dockerfile
            target: production
            image: moreshields/lol-tracker

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Go, Python, and protobuf are pre-installed in the base image

    - name: Generate protobuf code
      run: make proto

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # Need to use docker driver when running in container
        driver: docker

    - name: Log in to Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ matrix.image }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push ${{ matrix.service }} Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        target: ${{ matrix.target }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha,scope=${{ matrix.service }}
        cache-to: type=gha,mode=max,scope=${{ matrix.service }}