name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install protobuf compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Install protobuf tools
      run: make -C api install-tools

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('discord-client/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Cache Python dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('lol-tracker/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Generate protobuf code for discord-client
      working-directory: discord-client
      run: make proto

    - name: Download dependencies
      working-directory: discord-client
      run: go mod download

    - name: Setup Python virtual environment
      run: |
        python -m venv venv
        ./venv/bin/pip install --upgrade pip

    - name: Install lol-tracker dependencies
      working-directory: lol-tracker
      run: ../venv/bin/pip install -r requirements-dev.txt

    - name: Generate protobuf code for lol-tracker
      working-directory: lol-tracker
      run: make proto

    - name: Run discord-client unit tests
      working-directory: discord-client
      env:
        ENVIRONMENT: test
      run: go test -v -short ./...

    - name: Run discord-client integration tests
      working-directory: discord-client
      env:
        ENVIRONMENT: test
        TESTCONTAINERS_RYUK_DISABLED: true
      run: go test -v ./repository/...

    - name: Run lol-tracker tests
      working-directory: lol-tracker
      env:
        ENVIRONMENT: test
        TESTCONTAINERS_RYUK_DISABLED: true
        DATABASE_URL: postgresql://test:test@localhost:5432/test
      run: make test

    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 7